Add support for Poetry 1.6(#10)
arcesium/poetry-plugin-pypi-mirror pull request #11
Opened 2023-09-08 17:49 UTC by waketzheng

1. Add support for Poetry 1.6;
2. Upgrade dev dependencies;
3. Drop support for python<3.8.1 because of flake8 requires.

This version of the plugin supports Poetry
>= 1.3, < 1.7.

2023-09-11 01:29 UTC, JacobHenner requested changes
Thank you for your contribution!

Could you edit your commit(s) to include a DCO signature? I've just added instructions to the project's README: https://github.com/arcesium/poetry-plugin-pypi-mirror#sign-your-work

2023-09-11 01:29 UTC, JacobHenner commented on pyproject.toml
> -version = "0.3.2"
Could you leave this unincremented for now? I'll increment the version at release time.

2023-09-11 01:29 UTC, JacobHenner commented on src/poetry_plugin_pypi_mirror/plugins.py
> +
This change appears to have been made for poetry-core 1.3.0, approximately 1y ago: https://github.com/python-poetry/poetry-core/pull/482

2023-09-11 01:29 UTC, JacobHenner commented on pyproject.toml
> -python = "^3.7"
I don't think this comment is strictly necessary. Python 3.7 is EOL, supporting >= 3.8 only does not need further justification.

2023-09-11 13:43 UTC, waketzheng commented on src/poetry_plugin_pypi_mirror/plugins.py
> +
Great! Simple is better that complex~

2023-09-11 13:45 UTC, waketzheng commented
> Thank you for your contribution!
> 
> Could you edit your commit(s) to include a DCO signature? I've just added instructions to the project's README: https://github.com/arcesium/poetry-plugin-pypi-mirror#sign-your-work

Should I sign the old commit?

2023-09-11 13:58 UTC, JacobHenner commented
> > Thank you for your contribution!
> > Could you edit your commit(s) to include a DCO signature? I've just added instructions to the project's README: https://github.com/arcesium/poetry-plugin-pypi-mirror#sign-your-work
> 
> Should I sign the old commit?

Yes please. You can rebase your two commits into a single commit, and sign that commit. Then we should be good to go.

2023-09-12 13:00 UTC, waketzheng commented
@JacobHenner done.

2023-09-12 13:08 UTC, JacobHenner approved these changes

2023-09-12 13:10 UTC, merged